name: Flask CI/CDs

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: flask-app

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          cd app
          pip install -r requirements.txt

      # - name: Run Unit Tests
      #   run: |
      #     cd app
      #     pytest
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://localhost:9000

      # - name: SonarQube Quality Gate
      #   uses: SonarSource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} ./app

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag $IMAGE_NAME:${{ github.sha }} \
          ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ github.sha }}

          docker push \
          ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ github.sha }}

      - name: Helm Validation
        run: |
          cd flask
      
          helm lint . -f values-dev.yaml
          helm lint . -f values-qa.yaml
          helm lint . -f values-prod.yaml
      
          helm template flask . -f values-dev.yaml
          helm template flask . -f values-qa.yaml
          helm template flask . -f values-prod.yaml

      - name: Deploy to Dev
        run: |
          helm upgrade --install flask ./flask \
          -f flask/values-dev.yaml \
          -n dev --create-namespace

      - name: Smoke Test
        run: |
          kubectl get pods -n dev

  production:
    needs: build
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Production
        run: |
          helm upgrade --install flask ./flask \
          -f flask/values-prod.yaml \
          -n prod --create-namespace

      - name: Smoke Test
        run: |
          kubectl get pods -n prod

      - name: Rollback on Failure
        if: failure()
        run: |
          helm rollback flask
